import { FLAGS } from '../constants/flags';

// const FLAG_SELECTOR_OPTION_LIST = [
// 	{
// 		id: 'USA',
// 		name: 'US',
// 		displayText: 'US(1)',
// 		locale: 'en-US',
// 		flag: FLAGS[0],
// 	},
// 	{
// 		id: 'NGN',
// 		label: 'NG',
// 		displayText: 'NG',
// 		locale: 'en-ng',
// 		flag: FLAGS[6],
// 	},
// ];
// const FLAG_SELECTOR_OPTION_LIST = countryListAllIsoData.map(item => {})

const countryListAllIsoData = [
	{ code: 'AF', displayText: 'AFG', label: 'Afghanistan', id: '004' },
	{ code: 'AL', displayText: 'ALB', label: 'Albania', id: '008' },
	{ code: 'DZ', displayText: 'DZA', label: 'Algeria', id: '012' },
	{ code: 'AS', displayText: 'ASM', label: 'American Samoa', id: '016' },
	{ code: 'AD', displayText: 'AND', label: 'Andorra', id: '020' },
	{ code: 'AO', displayText: 'AGO', label: 'Angola', id: '024' },
	{ code: 'AI', displayText: 'AIA', label: 'Anguilla', id: '660' },
	{ code: 'AQ', displayText: 'ATA', label: 'Antarctica', id: '010' },
	{
		code: 'AG',
		displayText: 'ATG',
		label: 'Antigua and Barbuda',
		id: '028',
	},
	{ code: 'AR', displayText: 'ARG', label: 'Argentina', id: '032' },
	{ code: 'AM', displayText: 'ARM', label: 'Armenia', id: '051' },
	{ code: 'AW', displayText: 'ABW', label: 'Aruba', id: '533' },
	{ code: 'AU', displayText: 'AUS', label: 'Australia', id: '036' },
	{ code: 'AT', displayText: 'AUT', label: 'Austria', id: '040' },
	{ code: 'AZ', displayText: 'AZE', label: 'Azerbaijan', id: '031' },
	{ code: 'BS', displayText: 'BHS', label: 'Bahamas (the)', id: '044' },
	{ code: 'BH', displayText: 'BHR', label: 'Bahrain', id: '048' },
	{ code: 'BD', displayText: 'BGD', label: 'Bangladesh', id: '050' },
	{ code: 'BB', displayText: 'BRB', label: 'Barbados', id: '052' },
	{ code: 'BY', displayText: 'BLR', label: 'Belarus', id: '112' },
	{ code: 'BE', displayText: 'BEL', label: 'Belgium', id: '056' },
	{ code: 'BZ', displayText: 'BLZ', label: 'Belize', id: '084' },
	{ code: 'BJ', displayText: 'BEN', label: 'Benin', id: '204' },
	{ code: 'BM', displayText: 'BMU', label: 'Bermuda', id: '060' },
	{ code: 'BT', displayText: 'BTN', label: 'Bhutan', id: '064' },
	{
		code: 'BO',
		displayText: 'BOL',
		label: 'Bolivia (Plurinational State of)',
		id: '068',
	},
	{
		code: 'BQ',
		displayText: 'BES',
		label: 'Bonaire, Sint Eustatius and Saba',
		id: '535',
	},
	{
		code: 'BA',
		displayText: 'BIH',
		label: 'Bosnia and Herzegovina',
		id: '070',
	},
	{ code: 'BW', displayText: 'BWA', label: 'Botswana', id: '072' },
	{ code: 'BV', displayText: 'BVT', label: 'Bouvet Island', id: '074' },
	{ code: 'BR', displayText: 'BRA', label: 'Brazil', id: '076' },
	{
		code: 'IO',
		displayText: 'IOT',
		label: 'British Indian Ocean Territory (the)',
		id: '086',
	},
	{ code: 'BN', displayText: 'BRN', label: 'Brunei Darussalam', id: '096' },
	{ code: 'BG', displayText: 'BGR', label: 'Bulgaria', id: '100' },
	{ code: 'BF', displayText: 'BFA', label: 'Burkina Faso', id: '854' },
	{ code: 'BI', displayText: 'BDI', label: 'Burundi', id: '108' },
	{ code: 'CV', displayText: 'CPV', label: 'Cabo Verde', id: '132' },
	{ code: 'KH', displayText: 'KHM', label: 'Cambodia', id: '116' },
	{ code: 'CM', displayText: 'CMR', label: 'Cameroon', id: '120' },
	{ code: 'CA', displayText: 'CAN', label: 'Canada', id: '124' },
	{
		code: 'KY',
		displayText: 'CYM',
		label: 'Cayman Islands (the)',
		id: '136',
	},
	{
		code: 'CF',
		displayText: 'CAF',
		label: 'Central African Republic (the)',
		id: '140',
	},
	{ code: 'TD', displayText: 'TCD', label: 'Chad', id: '148' },
	{ code: 'CL', displayText: 'CHL', label: 'Chile', id: '152' },
	{ code: 'CN', displayText: 'CHN', label: 'China', id: '156' },
	{ code: 'CX', displayText: 'CXR', label: 'Christmas Island', id: '162' },
	{
		code: 'CC',
		displayText: 'CCK',
		label: 'Cocos (Keeling) Islands (the)',
		id: '166',
	},
	{ code: 'CO', displayText: 'COL', label: 'Colombia', id: '170' },
	{ code: 'KM', displayText: 'COM', label: 'Comoros (the)', id: '174' },
	{
		code: 'CD',
		displayText: 'COD',
		label: 'Congo (the Democratic Republic of the)',
		id: '180',
	},
	{ code: 'CG', displayText: 'COG', label: 'Congo (the)', id: '178' },
	{ code: 'CK', displayText: 'COK', label: 'Cook Islands (the)', id: '184' },
	{ code: 'CR', displayText: 'CRI', label: 'Costa Rica', id: '188' },
	{ code: 'HR', displayText: 'HRV', label: 'Croatia', id: '191' },
	{ code: 'CU', displayText: 'CUB', label: 'Cuba', id: '192' },
	{ code: 'CW', displayText: 'CUW', label: 'Curaçao', id: '531' },
	{ code: 'CY', displayText: 'CYP', label: 'Cyprus', id: '196' },
	{ code: 'CZ', displayText: 'CZE', label: 'Czechia', id: '203' },
	{ code: 'CI', displayText: 'CIV', label: "Côte d'Ivoire", id: '384' },
	{ code: 'DK', displayText: 'DNK', label: 'Denmark', id: '208' },
	{ code: 'DJ', displayText: 'DJI', label: 'Djibouti', id: '262' },
	{ code: 'DM', displayText: 'DMA', label: 'Dominica', id: '212' },
	{
		code: 'DO',
		displayText: 'DOM',
		label: 'Dominican Republic (the)',
		id: '214',
	},
	{ code: 'EC', displayText: 'ECU', label: 'Ecuador', id: '218' },
	{ code: 'EG', displayText: 'EGY', label: 'Egypt', id: '818' },
	{ code: 'SV', displayText: 'SLV', label: 'El Salvador', id: '222' },
	{ code: 'GQ', displayText: 'GNQ', label: 'Equatorial Guinea', id: '226' },
	{ code: 'ER', displayText: 'ERI', label: 'Eritrea', id: '232' },
	{ code: 'EE', displayText: 'EST', label: 'Estonia', id: '233' },
	{ code: 'SZ', displayText: 'SWZ', label: 'Eswatini', id: '748' },
	{ code: 'ET', displayText: 'ETH', label: 'Ethiopia', id: '231' },
	{
		code: 'FK',
		displayText: 'FLK',
		label: 'Falkland Islands (the) [Malvinas]',
		id: '238',
	},
	{
		code: 'FO',
		displayText: 'FRO',
		label: 'Faroe Islands (the)',
		id: '234',
	},
	{ code: 'FJ', displayText: 'FJI', label: 'Fiji', id: '242' },
	{ code: 'FI', displayText: 'FIN', label: 'Finland', id: '246' },
	{ code: 'FR', displayText: 'FRA', label: 'France', id: '250' },
	{ code: 'GF', displayText: 'GUF', label: 'French Guiana', id: '254' },
	{ code: 'PF', displayText: 'PYF', label: 'French Polynesia', id: '258' },
	{
		code: 'TF',
		displayText: 'ATF',
		label: 'French Southern Territories (the)',
		id: '260',
	},
	{ code: 'GA', displayText: 'GAB', label: 'Gabon', id: '266' },
	{ code: 'GM', displayText: 'GMB', label: 'Gambia (the)', id: '270' },
	{ code: 'GE', displayText: 'GEO', label: 'Georgia', id: '268' },
	{ code: 'DE', displayText: 'DEU', label: 'Germany', id: '276' },
	{ code: 'GH', displayText: 'GHA', label: 'Ghana', id: '288' },
	{ code: 'GI', displayText: 'GIB', label: 'Gibraltar', id: '292' },
	{ code: 'GR', displayText: 'GRC', label: 'Greece', id: '300' },
	{ code: 'GL', displayText: 'GRL', label: 'Greenland', id: '304' },
	{ code: 'GD', displayText: 'GRD', label: 'Grenada', id: '308' },
	{ code: 'GP', displayText: 'GLP', label: 'Guadeloupe', id: '312' },
	{ code: 'GU', displayText: 'GUM', label: 'Guam', id: '316' },
	{ code: 'GT', displayText: 'GTM', label: 'Guatemala', id: '320' },
	{ code: 'GG', displayText: 'GGY', label: 'Guernsey', id: '831' },
	{ code: 'GN', displayText: 'GIN', label: 'Guinea', id: '324' },
	{ code: 'GW', displayText: 'GNB', label: 'Guinea-Bissau', id: '624' },
	{ code: 'GY', displayText: 'GUY', label: 'Guyana', id: '328' },
	{ code: 'HT', displayText: 'HTI', label: 'Haiti', id: '332' },
	{
		code: 'HM',
		displayText: 'HMD',
		label: 'Heard Island and McDonald Islands',
		id: '334',
	},
	{ code: 'VA', displayText: 'VAT', label: 'Holy See (the)', id: '336' },
	{ code: 'HN', displayText: 'HND', label: 'Honduras', id: '340' },
	{ code: 'HK', displayText: 'HKG', label: 'Hong Kong', id: '344' },
	{ code: 'HU', displayText: 'HUN', label: 'Hungary', id: '348' },
	{ code: 'IS', displayText: 'ISL', label: 'Iceland', id: '352' },
	{ code: 'IN', displayText: 'IND', label: 'India', id: '356' },
	{ code: 'ID', displayText: 'IDN', label: 'Indonesia', id: '360' },
	{
		code: 'IR',
		displayText: 'IRN',
		label: 'Iran (Islamic Republic of)',
		id: '364',
	},
	{ code: 'IQ', displayText: 'IRQ', label: 'Iraq', id: '368' },
	{ code: 'IE', displayText: 'IRL', label: 'Ireland', id: '372' },
	{ code: 'IM', displayText: 'IMN', label: 'Isle of Man', id: '833' },
	{ code: 'IL', displayText: 'ISR', label: 'Israel', id: '376' },
	{ code: 'IT', displayText: 'ITA', label: 'Italy', id: '380' },
	{ code: 'JM', displayText: 'JAM', label: 'Jamaica', id: '388' },
	{ code: 'JP', displayText: 'JPN', label: 'Japan', id: '392' },
	{ code: 'JE', displayText: 'JEY', label: 'Jersey', id: '832' },
	{ code: 'JO', displayText: 'JOR', label: 'Jordan', id: '400' },
	{ code: 'KZ', displayText: 'KAZ', label: 'Kazakhstan', id: '398' },
	{ code: 'KE', displayText: 'KEN', label: 'Kenya', id: '404' },
	{ code: 'KI', displayText: 'KIR', label: 'Kiribati', id: '296' },
	{
		code: 'KP',
		displayText: 'PRK',
		label: "Korea (the Democratic People's Republic of)",
		id: '408',
	},
	{
		code: 'KR',
		displayText: 'KOR',
		label: 'Korea (the Republic of)',
		id: '410',
	},
	{ code: 'KW', displayText: 'KWT', label: 'Kuwait', id: '414' },
	{ code: 'KG', displayText: 'KGZ', label: 'Kyrgyzstan', id: '417' },
	{
		code: 'LA',
		displayText: 'LAO',
		label: "Lao People's Democratic Republic (the)",
		id: '418',
	},
	{ code: 'LV', displayText: 'LVA', label: 'Latvia', id: '428' },
	{ code: 'LB', displayText: 'LBN', label: 'Lebanon', id: '422' },
	{ code: 'LS', displayText: 'LSO', label: 'Lesotho', id: '426' },
	{ code: 'LR', displayText: 'LBR', label: 'Liberia', id: '430' },
	{ code: 'LY', displayText: 'LBY', label: 'Libya', id: '434' },
	{ code: 'LI', displayText: 'LIE', label: 'Liechtenstein', id: '438' },
	{ code: 'LT', displayText: 'LTU', label: 'Lithuania', id: '440' },
	{ code: 'LU', displayText: 'LUX', label: 'Luxembourg', id: '442' },
	{ code: 'MO', displayText: 'MAC', label: 'Macao', id: '446' },
	{ code: 'MG', displayText: 'MDG', label: 'Madagascar', id: '450' },
	{ code: 'MW', displayText: 'MWI', label: 'Malawi', id: '454' },
	{ code: 'MY', displayText: 'MYS', label: 'Malaysia', id: '458' },
	{ code: 'MV', displayText: 'MDV', label: 'Maldives', id: '462' },
	{ code: 'ML', displayText: 'MLI', label: 'Mali', id: '466' },
	{ code: 'MT', displayText: 'MLT', label: 'Malta', id: '470' },
	{
		code: 'MH',
		displayText: 'MHL',
		label: 'Marshall Islands (the)',
		id: '584',
	},
	{ code: 'MQ', displayText: 'MTQ', label: 'Martinique', id: '474' },
	{ code: 'MR', displayText: 'MRT', label: 'Mauritania', id: '478' },
	{ code: 'MU', displayText: 'MUS', label: 'Mauritius', id: '480' },
	{ code: 'YT', displayText: 'MYT', label: 'Mayotte', id: '175' },
	{ code: 'MX', displayText: 'MEX', label: 'Mexico', id: '484' },
	{
		code: 'FM',
		displayText: 'FSM',
		label: 'Micronesia (Federated States of)',
		id: '583',
	},
	{
		code: 'MD',
		displayText: 'MDA',
		label: 'Moldova (the Republic of)',
		id: '498',
	},
	{ code: 'MC', displayText: 'MCO', label: 'Monaco', id: '492' },
	{ code: 'MN', displayText: 'MNG', label: 'Mongolia', id: '496' },
	{ code: 'ME', displayText: 'MNE', label: 'Montenegro', id: '499' },
	{ code: 'MS', displayText: 'MSR', label: 'Montserrat', id: '500' },
	{ code: 'MA', displayText: 'MAR', label: 'Morocco', id: '504' },
	{ code: 'MZ', displayText: 'MOZ', label: 'Mozambique', id: '508' },
	{ code: 'MM', displayText: 'MMR', label: 'Myanmar', id: '104' },
	{ code: 'NA', displayText: 'NAM', label: 'Namibia', id: '516' },
	{ code: 'NR', displayText: 'NRU', label: 'Nauru', id: '520' },
	{ code: 'NP', displayText: 'NPL', label: 'Nepal', id: '524' },
	{ code: 'NL', displayText: 'NLD', label: 'Netherlands (the)', id: '528' },
	{ code: 'NC', displayText: 'NCL', label: 'New Caledonia', id: '540' },
	{ code: 'NZ', displayText: 'NZL', label: 'New Zealand', id: '554' },
	{ code: 'NI', displayText: 'NIC', label: 'Nicaragua', id: '558' },
	{ code: 'NE', displayText: 'NER', label: 'Niger (the)', id: '562' },
	{ code: 'NG', displayText: 'NGA', label: 'Nigeria', id: '566' },
	{ code: 'NU', displayText: 'NIU', label: 'Niue', id: '570' },
	{ code: 'NF', displayText: 'NFK', label: 'Norfolk Island', id: '574' },
	{
		code: 'MP',
		displayText: 'MNP',
		label: 'Northern Mariana Islands (the)',
		id: '580',
	},
	{ code: 'NO', displayText: 'NOR', label: 'Norway', id: '578' },
	{ code: 'OM', displayText: 'OMN', label: 'Oman', id: '512' },
	{ code: 'PK', displayText: 'PAK', label: 'Pakistan', id: '586' },
	{ code: 'PW', displayText: 'PLW', label: 'Palau', id: '585' },
	{
		code: 'PS',
		displayText: 'PSE',
		label: 'Palestine, State of',
		id: '275',
	},
	{ code: 'PA', displayText: 'PAN', label: 'Panama', id: '591' },
	{ code: 'PG', displayText: 'PNG', label: 'Papua New Guinea', id: '598' },
	{ code: 'PY', displayText: 'PRY', label: 'Paraguay', id: '600' },
	{ code: 'PE', displayText: 'PER', label: 'Peru', id: '604' },
	{ code: 'PH', displayText: 'PHL', label: 'Philippines (the)', id: '608' },
	{ code: 'PN', displayText: 'PCN', label: 'Pitcairn', id: '612' },
	{ code: 'PL', displayText: 'POL', label: 'Poland', id: '616' },
	{ code: 'PT', displayText: 'PRT', label: 'Portugal', id: '620' },
	{ code: 'PR', displayText: 'PRI', label: 'Puerto Rico', id: '630' },
	{ code: 'QA', displayText: 'QAT', label: 'Qatar', id: '634' },
	{
		code: 'MK',
		displayText: 'MKD',
		label: 'Republic of North Macedonia',
		id: '807',
	},
	{ code: 'RO', displayText: 'ROU', label: 'Romania', id: '642' },
	{
		code: 'RU',
		displayText: 'RUS',
		label: 'Russian Federation (the)',
		id: '643',
	},
	{ code: 'RW', displayText: 'RWA', label: 'Rwanda', id: '646' },
	{ code: 'RE', displayText: 'REU', label: 'Réunion', id: '638' },
	{ code: 'BL', displayText: 'BLM', label: 'Saint Barthélemy', id: '652' },
	{
		code: 'SH',
		displayText: 'SHN',
		label: 'Saint Helena, Ascension and Tristan da Cunha',
		id: '654',
	},
	{
		code: 'KN',
		displayText: 'KNA',
		label: 'Saint Kitts and Nevis',
		id: '659',
	},
	{ code: 'LC', displayText: 'LCA', label: 'Saint Lucia', id: '662' },
	{
		code: 'MF',
		displayText: 'MAF',
		label: 'Saint Martin (French part)',
		id: '663',
	},
	{
		code: 'PM',
		displayText: 'SPM',
		label: 'Saint Pierre and Miquelon',
		id: '666',
	},
	{
		code: 'VC',
		displayText: 'VCT',
		label: 'Saint Vincent and the Grenadines',
		id: '670',
	},
	{ code: 'WS', displayText: 'WSM', label: 'Samoa', id: '882' },
	{ code: 'SM', displayText: 'SMR', label: 'San Marino', id: '674' },
	{
		code: 'ST',
		displayText: 'STP',
		label: 'Sao Tome and Principe',
		id: '678',
	},
	{ code: 'SA', displayText: 'SAU', label: 'Saudi Arabia', id: '682' },
	{ code: 'SN', displayText: 'SEN', label: 'Senegal', id: '686' },
	{ code: 'RS', displayText: 'SRB', label: 'Serbia', id: '688' },
	{ code: 'SC', displayText: 'SYC', label: 'Seychelles', id: '690' },
	{ code: 'SL', displayText: 'SLE', label: 'Sierra Leone', id: '694' },
	{ code: 'SG', displayText: 'SGP', label: 'Singapore', id: '702' },
	{
		code: 'SX',
		displayText: 'SXM',
		label: 'Sint Maarten (Dutch part)',
		id: '534',
	},
	{ code: 'SK', displayText: 'SVK', label: 'Slovakia', id: '703' },
	{ code: 'SI', displayText: 'SVN', label: 'Slovenia', id: '705' },
	{ code: 'SB', displayText: 'SLB', label: 'Solomon Islands', id: '090' },
	{ code: 'SO', displayText: 'SOM', label: 'Somalia', id: '706' },
	{ code: 'ZA', displayText: 'ZAF', label: 'South Africa', id: '710' },
	{
		code: 'GS',
		displayText: 'SGS',
		label: 'South Georgia and the South Sandwich Islands',
		id: '239',
	},
	{ code: 'SS', displayText: 'SSD', label: 'South Sudan', id: '728' },
	{ code: 'ES', displayText: 'ESP', label: 'Spain', id: '724' },
	{ code: 'LK', displayText: 'LKA', label: 'Sri Lanka', id: '144' },
	{ code: 'SD', displayText: 'SDN', label: 'Sudan (the)', id: '729' },
	{ code: 'SR', displayText: 'SUR', label: 'Suriname', id: '740' },
	{
		code: 'SJ',
		displayText: 'SJM',
		label: 'Svalbard and Jan Mayen',
		id: '744',
	},
	{ code: 'SE', displayText: 'SWE', label: 'Sweden', id: '752' },
	{ code: 'CH', displayText: 'CHE', label: 'Switzerland', id: '756' },
	{
		code: 'SY',
		displayText: 'SYR',
		label: 'Syrian Arab Republic',
		id: '760',
	},
	{ code: 'TW', displayText: 'TWN', label: 'Taiwan', id: '158' },
	{ code: 'TJ', displayText: 'TJK', label: 'Tajikistan', id: '762' },
	{
		code: 'TZ',
		displayText: 'TZA',
		label: 'Tanzania, United Republic of',
		id: '834',
	},
	{ code: 'TH', displayText: 'THA', label: 'Thailand', id: '764' },
	{ code: 'TL', displayText: 'TLS', label: 'Timor-Leste', id: '626' },
	{ code: 'TG', displayText: 'TGO', label: 'Togo', id: '768' },
	{ code: 'TK', displayText: 'TKL', label: 'Tokelau', id: '772' },
	{ code: 'TO', displayText: 'TON', label: 'Tonga', id: '776' },
	{
		code: 'TT',
		displayText: 'TTO',
		label: 'Trinidad and Tobago',
		id: '780',
	},
	{ code: 'TN', displayText: 'TUN', label: 'Tunisia', id: '788' },
	{ code: 'TR', displayText: 'TUR', label: 'Turkey', id: '792' },
	{ code: 'TM', displayText: 'TKM', label: 'Turkmenistan', id: '795' },
	{
		code: 'TC',
		displayText: 'TCA',
		label: 'Turks and Caicos Islands (the)',
		id: '796',
	},
	{ code: 'TV', displayText: 'TUV', label: 'Tuvalu', id: '798' },
	{ code: 'UG', displayText: 'UGA', label: 'Uganda', id: '800' },
	{ code: 'UA', displayText: 'UKR', label: 'Ukraine', id: '804' },
	{
		code: 'AE',
		displayText: 'ARE',
		label: 'United Arab Emirates (the)',
		id: '784',
	},
	{
		code: 'GB',
		displayText: 'GBR',
		label: 'United Kingdom of Great Britain and Northern Ireland (the)',
		id: '826',
	},
	{
		code: 'UM',
		displayText: 'UMI',
		label: 'United States Minor Outlying Islands (the)',
		id: '581',
	},
	{
		code: 'US',
		displayText: 'USA',
		label: 'United States of America (the)',
		id: '840',
	},
	{ code: 'UY', displayText: 'URY', label: 'Uruguay', id: '858' },
	{ code: 'UZ', displayText: 'UZB', label: 'Uzbekistan', id: '860' },
	{ code: 'VU', displayText: 'VUT', label: 'Vanuatu', id: '548' },
	{
		code: 'VE',
		displayText: 'VEN',
		label: 'Venezuela (Bolivarian Republic of)',
		id: '862',
	},
	{ code: 'VN', displayText: 'VNM', label: 'Viet Nam', id: '704' },
	{
		code: 'VG',
		displayText: 'VGB',
		label: 'Virgin Islands (British)',
		id: '092',
	},
	{
		code: 'VI',
		displayText: 'VIR',
		label: 'Virgin Islands (U.S.)',
		id: '850',
	},
	{ code: 'WF', displayText: 'WLF', label: 'Wallis and Futuna', id: '876' },
	{ code: 'EH', displayText: 'ESH', label: 'Western Sahara', id: '732' },
	{ code: 'YE', displayText: 'YEM', label: 'Yemen', id: '887' },
	{ code: 'ZM', displayText: 'ZMB', label: 'Zambia', id: '894' },
	{ code: 'ZW', displayText: 'ZWE', label: 'Zimbabwe', id: '716' },
	{ code: 'AX', displayText: 'ALA', label: 'Åland Islands', id: '248' },
];
// const FLAG_SELECTOR_OPTION_LIST = countryListAllIsoData.map((item) => ({
// 	id: item.displayText, //'USA',
// 	name: item.code, //'US',
// 	displayText: item.displayText, //'US(1)',
// 	locale: 'en-US',
// 	flag: require(`../@static/flags/${item.code.toLocaleLowerCase()}.svg`),
// }));
export default countryListAllIsoData;
// require('../@static/flags/');
